speaker_encoder:
  speaker_encoder_hidden: 256

transformer:
  encoder_layer: 4
  encoder_head: 2
  encoder_hidden: 192
  conv_filter_size: 768
  conv_kernel_size: [9, 1]
  encoder_dropout: 0.5
  decoder_dropout: 0.5

posterior_encoder:
  posterior_encoder_kernel_size: 5 
  posterior_encoder_dilation_rate: 1 
  posterior_encoder_n_layers: 16 
  
residual_coupling_block:
  residual_coupling_block_kernel_size: 5
  residual_coupling_block_dilation_rate: 1
  residual_coupling_block_n_layers: 4
  residual_coupling_block_n_flows: 4

variance_predictor:
  filter_size: 256
  kernel_size: 3
  dropout: 0.1
  cwt_hidden_size: 128
  cwt_std_scale: 0.8
  cwt_out_dims: 11
  cwt_stats_out_dims: 2

variance_embedding:
  energy_quantization: "linear" # support 'linear' or 'log', 'log' is allowed only if the energy values are not normalized during preprocessing
  n_bins: 256

temperature: 0.0005

max_seq_len: 1000
